platform :ios, '13.0'
use_frameworks!

target 'MetroSearch' do
  
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'NVActivityIndicatorView'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'IQKeyboardManagerSwift'
  
  target 'MetroSearchTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest'
    pod 'RxBlocking'
  end
  
end
